version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: notas_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LIONcito129
      POSTGRES_DB: gestion_notas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # este es el Dockerfile normal, NO el prod
    container_name: notas_backend_dev
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:LIONcito129@db:5432/gestion_notas?schema=public"
      PORT: 3000
      JWT_SECRET: "clave_super_secreta_para_firmar_tokens_gestion_notas"
      NODE_ENV: "development"
    ports:
      - "3000:3000"

volumes:
  postgres_data_dev:
